name: Build Mod

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Ensure Gradle wrapper is executable
        run: chmod +x ./gradlew

      - name: Restore Gradle & Loom caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build mod
        run: ./gradlew --no-daemon clean build

      - name: Upload built mod jar
        uses: actions/upload-artifact@v4
        with:
          name: fabric-permissions-api
          path: build/libs/*.jar
